#!/bin/bash
if [[ $# -eq 0 ]] ; then
	echo "Falta parámetro. Uso:"
	echo "$(basename $0) output_file.pdf input_file1.pdf input_file2.pdf"
	exit 0
fi
gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dAutoRotatePages=/None -sOutputFile=$1 $2 $3
